- hosts: dockerhost
  become: true

  tasks:
    - name: Stop existing container
      command: docker stop regapp
      ignore_errors: yes

    - name: Remove existing container
      command: docker rm regapp
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name regapp -p 8080:8080 regapp:latest
